---

replicaCount: 2
labels:
  - wini-gasthaus-website
resourcesName: wini-gasthaus-website

backend:
  resourcesName: wini-gasthaus-backend-service
  path: /api/
  port: 80

image:
  repository: dominikhillmann/wini-gasthaus-website
  pullPolicy: IfNotPresent
  # The image tag will always be determined in the pipeline.
  # It will follow the convention "$(< VERSION).$PR_NUMBER$([ $is_test_env ] && echo -stage)"
  tag: "TBD"

service:
  type: ClusterIP
  port: 80

resources: {}
