version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: gitsubmodule
    directory: /themes
    schedule:
      interval: daily
