baseURL = 'https://gasthaus-wini.com/'
languageCode = 'de'
title = 'Gasthaus Wini'
theme = 'tella'

defaultContentLanguage = 'de'

defaultContentLanguageInSubdir = false

[params]

  mainSections = ['reviews']
  googleFonts = true
  underConstructionBanner = true

  [params.logo]
    main = "/img/logo-gasthaus-wini.png"
    alt = "Gasthaus Wini"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Gasthaus Wini"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "booking"
    name = "Buchung"
    url = "/booking/"
    weight = 1

  [[menu.main]]
    identifier = "reviews"
    name = "Bewertungen"
    url = "/reviews/"
    weight = 2

  [[menu.main]]
    identifier = "rules"
    name = "Hausordnung"
    url = "/rules/"
    weight = 3

  [[menu.main]]
    identifier = "language"
    name = "English version"
    url = "/en/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "English version"
    url = "/en/"
    weight = 2
  
  [[menu.footer]]
    name = "Impressum"
    url = "/imprint"
    weight = 3

  # [[menu.footer]]
  #   name = "Github"
  #   url = "https://github.com/opera7133/tella"
  #   pre = "<i class='icon-github text-2xl'></i>"
  #   weight = 3

[languages]

  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'Gasthaus Wini'
    weight = 1
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Gasthaus Wini'
    weight = 2

      [languages.en.params.logo]
        alt = "Gasthaus Wini"

      [languages.en.menu]
        # Header menu
        [[languages.en.menu.main]]
          identifier = "booking"
          name = "Booking"
          url = "/en/booking/"
          weight = 1
        [[languages.en.menu.main]]
          identifier = "reviews"
          name = "Reviews"
          url = "/en/reviews/"
          weight = 2
        [[languages.en.menu.main]]
          identifier = "rules"
          name = "House Rules"
          url = "/en/rules/"
          weight = 3
        [[languages.en.menu.main]]
          identifier = "language"
          name = "Deutsche Version"
          url = "/de/"
          weight = 4
        # Footer Menu
        [[languages.en.menu.footer]]
          name = "Home"
          url = "/en/"
          weight = 1

        [[languages.en.menu.footer]]
          name = "Deutsche Version"
          url = "/"
          weight = 2
        
        [[languages.en.menu.footer]]
          name = "Imprint"
          url = "/en/imprint/"
          weight = 3
