---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wini-gasthaus-website
  
spec:
  secretName: wini-gasthaus-website
  dnsNames:
    - gasthaus-wini.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

