---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.resourcesName }}
  
spec:
  secretName: {{ .Values.ingress.tlsSecretName }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
