---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcesName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.resourcesName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.resourcesName }}
    spec:
      containers:
        - name: {{ .Values.resourcesName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}{{ if eq .Values.environment "test" }}-stage{{ else }}{{ end }}
          ports:
            - containerPort: {{ .Values.service.port }}
