---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourcesName }}
  labels:
    app: {{ .Values.resourcesName }}

spec:
  ports:
    - name: http-server
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.resourcesName }}
