---
apiVersion: v1
kind: Service
metadata:
  name: wini-gasthaus-website
  labels:
    app: wini-gasthaus-website

spec:
  ports:
    - name: http-server
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wini-gasthaus-website
