name: Main branch workflow

on:
  push:
    branches:
      - main

jobs:
  main-branch-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          image_name="$DOCKERHUB_USERNAME/wini-gasthaus-website:$(cat VERSION)"
          docker build -t "${image_name}" .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - name: Push prod version to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          image_name="$DOCKERHUB_USERNAME/wini-gasthaus-website:$(cat VERSION)"
          docker push "${image_name}"

      - name: Deploy to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_B64 }}
        with:
          args: |
            helm upgrade --install wini-gasthaus-website chart/ --install -n wini-prod

  create-version-tag:
    runs-on: ubuntu-latest
    needs: main-branch-deployment
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create version tag
        env:
          GIT_MAIL_ADDRESS: "${{ secrets.GIT_MAIL_ADDRESS }}"
        run: |
          version="v$(cat VERSION)"
          git config --local user.email "$GIT_MAIL_ADDRESS"
          git config --local user.name "Dominik-Hillmann"
          git tag "$version"
          git push --tags
